# <u><mark>README<mark></u>

### Research Question

<span style="color:red">
    
”How has the housing market changed over the period of a decade across the fifty U.S, states and
have these housing markets in these states remained relatively similar throughout this time frame,
or have they experienced either a substantial growth or decline in their markets?"
</span>
### Descirption of Each Dataset Used

### Which dataset used when joining, and join explanation (column, join type, row counts before and after)

<span style="color:red">

- The option we chose for the joining of a second dataset is a dataset that was found using the same source that we used to find the original data set.
- The second dataset is relevant to our research question because it still involves the housing market within almost the same time period (one month difference between the datasets) but it adds a new categorical variable that determines if the homes that were sold in specifc states were either luxury or otherwise. This new dataset also denotes the amounts of listings for each category. This dataset will allow us to determine how the housing market across states has changed in regards to luxury and non-luxury homes.
</span>

### A short summmary of the cleaning steps applied in Part 2F

### Final dataset shape (rows $\cdot$ columns)

### AI use disclosure

# Part 0: Proposal Revisit

1.  What changed? State which of the following applies: I changed my research question, I
changed my dataset, I changed both, or I changed neither.

<span style="color:red"> 

- The reasearch question for this project and the dataset has not been changed since our group has deemed that the aforementioned  was satisfactory.

</span>

3. On what basis? Explain the evidence behind your decision in 3 to 5 sentences. Strong
reasons are tied to the data itself. Examples include:

3.1. Scope: the data did not cover the population, region, or time period your question
needs.

<span style="color:red">
    
- The dataset our team has discovered for the purposes of answering the project question covered the entire United States, which includes all 50 states. The scope of this data is necessary to answer our team's question. Furthermore, the data was shown in our dataset fits the time period which our team's questions is focused on.

</span>

3.2. Granularity: the rows were too coarse (for example, state-level averages when you
needed individual records) or too fine to answer the question directly.

<span style="color:red">

- In regards to the granularity, our team believes that the data is granular enough to answer the question directly. Our question only needs state level avergaes of the housing market and not specific locations within a state.
</span>

3.3. Temporality: the data was outdated, or the date fields did not mean what you assumed.

<span style="color:red">
    
- The datset that our team is using to answer the research question is not outdated and the data fields are exactly what we need to answer the question.
</span>

3.4. Faithfulness: too many missing values, suspicious defaults, or duplicates to trust the
results.

<span style="color:red">

- There are null values in the data, but not enough to not trust the results. There also appears to be no suspicious defaults or duplicates
</span>
3.5. Structure: the data was nested or messy enough that it could not reasonably be made
rectangular.

<span style="color:red">

- The data itself is rectangular in nature so no modifications needed to be made to make it rectangular.
</span>
3.6. Practical constraints: fewer than 1,000 rows, a restrictive license, or instructor feedback
from Phase 1.

<span style="color:red">

- There are no practical contraints; there are more than 6000 rows, and the data itself is public so no license is required.
</span>

In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_rows',20)

# Part 1: Dataset Preparation and Joins

## 1A. Choose Your Second Dataset (Required)

In [85]:
df2 = pd.read_csv("./data/redfin_luxury_both_all_states_key_metrics_2016_Jan_to_2026_Jul.csv")
df = pd.read_csv("../G1 Project Proposal/data/redfin_housing_market_monthly_all_states_key_metrics_2016_Jan_to_2026_Aug.csv")

df2.head(3)

,LAST UPDATED,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION TYPE,REGION NAME,PRICE BUCKET,MEDIAN SALE PRICE ($),MEDIAN DAYS ON MARKET (DAYS),ACTIVE LISTINGS,PENDING SALES
0,2026-08-15,Rolling 3 months,2026-05-01,2026-07-31,State,Alabama,Luxury,981284,61,2413,1163
1,2026-08-15,Rolling 3 months,2026-04-01,2026-06-30,State,Alabama,Luxury,993821,56,2423,1197
2,2026-08-15,Rolling 3 months,2026-03-01,2026-05-31,State,Alabama,Luxury,989858,55,2385,1194

In [86]:
df.head(3)

,LAST UPDATED,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION ID,REGION TYPE,REGION NAME,HOMES SOLD,HOMES SOLD YOY (%),MEDIAN SALE PRICE NSA ($),MEDIAN SALE PRICE NSA YOY (%),MEDIAN DAYS ON MARKET (DAYS),MEDIAN DAYS ON MARKET YOY (DAYS),NEW LISTINGS,NEW LISTINGS YOY (%),ACTIVE LISTINGS,ACTIVE LISTINGS YOY (%),PENDING SALES,PENDING SALES YOY (%),MEDIAN NEW LISTING PRICE PER SQ.FT. ($),MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%)
0,2026-09-03,Monthly,2026-08-01,2026-08-31,1,State,Alabama,5201.0,-1.38,301146.0,2.12,66.0,4.0,6918.0,4.05,31040.0,6.16,6421.0,4.94,159.31,-0.16
1,2026-09-03,Monthly,2026-08-01,2026-08-31,3,State,Alaska,728.0,3.76,415271.0,2.54,30.0,-2.0,903.0,12.35,2788.0,10.95,798.0,0.32,256.11,5.43
2,2026-09-03,Monthly,2026-08-01,2026-08-31,5,State,Arizona,8207.0,-1.08,428217.0,-0.88,66.0,-4.0,10765.0,-0.39,48440.0,-0.03,9513.0,-3.84,259.61,1.28

## 1B. Merge Requirements

• The column(s) you joined on

<span style="color:red">

- I joined on the REGION TYPE, REGION NAME, and PERIOD BEGIN columns since these are the three columns that these two datasets share the most with each other. For the PERIOD BEGIN column, we organized the datasets by only including the values from the 2nd dataset that share the PERIOD BEGIN date with the frst dataset. 
</span>
• The type of join used (inner, left, right, or outer)

<span style="color:red">

- I used inner join
</span>
• Number of rows in each dataset before the join

<span style="color:red">

- first dataset: 6647
- second dataset: 12750
</span>
• Number of rows in the merged result

<span style="color:red">

- 12750
</span>
• Why the row count changed, stayed the same, or might have dropped

<span style="color:red">

- The row count for the merged dataset stayed the same as the row count for the second dataset. The reason why this happened is because, since the two datasets were merged on their beginning dates, the dataset with the larger amount of of rows will decide the total rows for the merged dataset. The reason why is because, although the right half of the data is unique, there would be duplicates of the left half of the data to match the number of rows of the right half.
</span>
• New: The granularity of each dataset before the join (for example, “one row per week” versus
“one row per transaction”), and what you had to do to make the two line up (for example,
converting daily dates to week start dates, or aggregating your data to weekly before joining)

<span style="color:red">

- The granularity of the first dataset is that it had one row per month, which is divided into start dates and end dates.
- The granularity of the second dataset was that it had a row for every 3 months, which is also seperated into start and end dates.
- We could not line up the datasets on their respective dates. Instead, we merged the datasets based on their start dates so that the data from the first dataset and second dataset correspond to each other in regards to the start date of their data collection. Because of this, our team is then able to make comparisons between the two datasets because they will have the same start date. This prevents us from making comparisons between the first and second dataset with enitrely different dates. The only difference presented in the merged dataset is the end date for the left half of the data and the right half.
</span>
• New: Whether your join key is unique in each table. Check this with df[col].is_unique
or df[col].duplicated().sum() and explain what a non-unique key would do to your row
count.

<span style="color:red">

- All of the columns that we joined on for the merge have duplicates in them. In regards to the start and end dates, these duplicates stem from the fact that there are the exact same dates for different states. The reason why there are duplicates for region names is because the name of every state is repeated for every new month that passes. For region type, the region is all states so the entire column has 'state' as the region type. Despite these duplicates in singular columns, there aren't enitre duplicates for the full rows of the first or second datasets. However, the merged dataset has its left side duplicated for each original entry to match the same number of rows as the right side.
- Through reading about it during lectures and testing what a non-unqiue join key would do to the number of rows, the number of rows for the dataset would skyrocket in quantity. After having tested this by joining on a singular non-unique key, the number of rows for the merged dataset shot up to more than a million . This is known as a many-to-many join, where the number of rows exlode in number.
</span>

In [87]:
print(df.columns.tolist())
print("\n\n\n")
print(df2.columns.tolist())

print("\n\n")
print(df.dtypes)
print(df2.dtypes)


df_merge = pd.merge(df,df2,on=['REGION TYPE','REGION NAME', 'PERIOD BEGIN'],how='inner')

print(df_merge.dtypes)

print("\n\n")
print(f"{len(df)} + {len(df2)} + {len(df_merge)}")

df_merge.tail()


print("\n\n")

print(f"for first dataset ('REGION TYPE'): {df['REGION TYPE'].duplicated().sum()}\n\n\n")
print(f"for second dataset ('REGION TYPE'): {df['REGION TYPE'].duplicated().sum()}\n\n\n")
print(f"for merged dataset ('REGION TYPE'): {df['REGION TYPE'].duplicated().sum()}\n\n\n")

print(f"for first dataset ('REGION NAME'): {df['REGION NAME'].duplicated().sum()}\n\n\n")
print(f"for second dataset ('REGION NAME'): {df['REGION NAME'].duplicated().sum()}\n\n\n")
print(f"for merged dataset ('REGION NAME'): {df['REGION NAME'].duplicated().sum()}\n\n\n")

print(f"for first dataset ('PERIOD BEGIN'): {df['PERIOD BEGIN'].duplicated().sum()}\n\n\n")
print(f"for second dataset ('PERIOD BEGIN'): {df['PERIOD BEGIN'].duplicated().sum()}\n\n\n")
print(f"for merged dataset ('PERIOD BEGIN'): {df['PERIOD BEGIN'].duplicated().sum()}\n\n\n")

['LAST UPDATED', 'FREQUENCY', 'PERIOD BEGIN', 'PERIOD END', 'REGION ID', 'REGION TYPE', 'REGION NAME', 'HOMES SOLD', 'HOMES SOLD YOY (%)', 'MEDIAN SALE PRICE NSA ($)', 'MEDIAN SALE PRICE NSA YOY (%)', 'MEDIAN DAYS ON MARKET (DAYS)', 'MEDIAN DAYS ON MARKET YOY (DAYS)', 'NEW LISTINGS', 'NEW LISTINGS YOY (%)', 'ACTIVE LISTINGS', 'ACTIVE LISTINGS YOY (%)', 'PENDING SALES', 'PENDING SALES YOY (%)', 'MEDIAN NEW LISTING PRICE PER SQ.FT. ($)', 'MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%)']




['LAST UPDATED', 'FREQUENCY', 'PERIOD BEGIN', 'PERIOD END', 'REGION TYPE', 'REGION NAME', 'PRICE BUCKET', 'MEDIAN SALE PRICE ($)', 'MEDIAN DAYS ON MARKET (DAYS)', 'ACTIVE LISTINGS', 'PENDING SALES']



LAST UPDATED                                    object
FREQUENCY                                       object
PERIOD BEGIN                                    object
PERIOD END                                      object
REGION ID                                        int64
                                                ...
ACTIVE LISTINGS YOY (%)                        float64
PENDING SALES                                  float64
PENDING SALES YOY (%)                          float64
MEDIAN NEW LISTING PRICE PER SQ.FT. ($)        float64
MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%)    float64
Length: 21, dtype: object
LAST UPDATED                    object
FREQUENCY                       object
PERIOD BEGIN                    object
PERIOD END                      object
REGION TYPE                     object
                                 ...
PRICE BUCKET                    object
MEDIAN SALE PRICE ($)            int64
MEDIAN DAYS ON MARKET (DAYS)     int64
ACTIVE LISTINGS                  int64
PENDING SALES                    int64
Length: 11, dtype: object
LAST UPDATED_x                    object
FREQUENCY_x                       object
PERIOD BEGIN                      object
PERIOD END_x                      object
REGION ID                          int64
                                   ...
PRICE BUCKET                      object
MEDIAN SALE PRICE ($)              int64
MEDIAN DAYS ON MARKET (DAYS)_y     int64
ACTIVE LISTINGS_y                  int64
PENDING SALES_y                    int64
Length: 29, dtype: object



6647 + 12750 + 12750



for first dataset ('REGION TYPE'): 6646



for second dataset ('REGION TYPE'): 6646



for merged dataset ('REGION TYPE'): 6646



for first dataset ('REGION NAME'): 6593



for second dataset ('REGION NAME'): 6593



for merged dataset ('REGION NAME'): 6593



for first dataset ('PERIOD BEGIN'): 6519



for second dataset ('PERIOD BEGIN'): 6519



for merged dataset ('PERIOD BEGIN'): 6519

## 1C. Final Working Dataset Requirements

The final working dataset that our team chooses to use for the rest of this phase is the original dataset before the merge.

The dataset that we chose contains:

- more than 6000 rows
- more than 6 meaningful columns
- more than one categorical variable
- more than one numerical variable

In [88]:
print(df.shape)
print("\n\n")
df.info()
print("\n\n")
df.describe()

(6647, 21)



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6647 entries, 0 to 6646
Data columns (total 21 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   LAST UPDATED                                 6647 non-null   object
 1   FREQUENCY                                    6647 non-null   object
 2   PERIOD BEGIN                                 6647 non-null   object
 3   PERIOD END                                   6647 non-null   object
 4   REGION ID                                    6647 non-null   int64
 5   REGION TYPE                                  6647 non-null   object
 6   REGION NAME                                  6647 non-null   object
 7   HOMES SOLD                                   6528 non-null   float64
 8   HOMES SOLD YOY (%)                           6528 non-null   float64
 9   MEDIAN SALE PRICE NSA ($)                    6528 non-null   float64
 10  MEDIAN SALE PRICE NSA YOY (%)                6528 non-null   float64
 11  MEDIAN DAYS ON MARKET (DAYS)                 6528 non-null   float64
 12  MEDIAN DAYS ON MARKET YOY (DAYS)             6528 non-null   float64
 13  NEW LISTINGS                                 6529 non-null   float64
 14  NEW LISTINGS YOY (%)                         6528 non-null   float64
 15  ACTIVE LISTINGS                              6533 non-null   float64
 16  ACTIVE LISTINGS YOY (%)                      6533 non-null   float64
 17  PENDING SALES                                6528 non-null   float64
 18  PENDING SALES YOY (%)                        6528 non-null   float64
 19  MEDIAN NEW LISTING PRICE PER SQ.FT. ($)      6529 non-null   float64
 20  MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%)  6528 non-null   float64
dtypes: float64(14), int64(1), object(6)
memory usage: 1.1+ MB

,REGION ID,HOMES SOLD,HOMES SOLD YOY (%),MEDIAN SALE PRICE NSA ($),MEDIAN SALE PRICE NSA YOY (%),MEDIAN DAYS ON MARKET (DAYS),MEDIAN DAYS ON MARKET YOY (DAYS),NEW LISTINGS,NEW LISTINGS YOY (%),ACTIVE LISTINGS,ACTIVE LISTINGS YOY (%),PENDING SALES,PENDING SALES YOY (%),MEDIAN NEW LISTING PRICE PER SQ.FT. ($),MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%)
count,6647.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6528.000000,6529.000000,6528.000000,6533.000000,6533.000000,6528.000000,6528.000000,6529.000000,6528.000000
mean,26.577102,6856.473346,0.882160,313916.143995,6.504786,51.922335,-3.112745,8113.187318,1.106043,29526.809735,-1.721719,7809.323529,1.544508,188.390435,6.106578
std,15.202091,7304.190142,14.134984,130409.562000,5.652265,22.040611,10.917122,8921.406556,30.341742,34269.110832,12.775259,8532.624110,19.665601,99.255180,5.221785
min,1.000000,480.000000,-58.280000,115000.000000,-19.730000,0.000000,-67.000000,1.000000,-94.520000,1.000000,-39.540000,461.000000,-82.210000,76.410000,-32.780000
25%,13.000000,1761.250000,-4.320000,220000.000000,2.960000,35.000000,-9.000000,2068.000000,-4.262500,7537.000000,-10.050000,1877.000000,-5.570000,127.880000,2.850000
50%,26.000000,4617.000000,1.550000,277500.000000,5.710000,49.000000,-2.000000,5195.000000,1.370000,19126.000000,-2.850000,5278.500000,1.060000,159.750000,5.300000
75%,39.000000,9508.500000,6.810000,377625.000000,9.160000,66.000000,4.000000,10825.000000,6.100000,36945.000000,6.200000,10610.250000,7.062500,216.260000,8.482500
max,60.000000,48549.000000,163.240000,800000.000000,44.150000,141.000000,55.000000,50939.000000,1689.950000,232647.000000,64.830000,54605.000000,811.260000,1221.780000,45.420000

## 1D. Column Selection and Classification

| Column Name | dtype  | Variable Type | Justification | Relevance to Question |
|----------|----------|----------|----------|----------|
| PERIOD BEGIN    | object (to be converted)     | Quantitative Discrete     | represents the date, cannot be subdivided     | shows the beginning day, month, and year the data in the current row is describing     |
| PERIOD END    | object (to be converted)     | Quantitative Discrete     |  represents the date, cannot be subdivided     | shows the ending day, month, and year the data in the current row is describing     |
| REGION NAME| object     | Qualitative Nominal     | cateogircal value to describe state names, has no order     | This is necessary to identify which states the current row's data belongs to    |
| HOMES SOLD| float64| Quantitative Discrete| number of homes sold are counted and can only be whole numbers| This is necessary to find out how many homes were sold in a state|
| MEDIAN SALE PRICE NSA ($)| float64| Quantitative Continuous|represents price, can take decimal values | helps gauge the price of homes in a state |
| ACTIVE LISTINGS| float64| Quantitative Discrete| number of listings are counted and cannot be subdivided; must be whole numbers | allows us to see how many homes are listed for sale in a state|
| NEW LISTINGS| float64| Quantitative Discrete| number of new homes for sale are counted, cannot be subdivided | necessary for determining how many new homes are sold in a state in a certain amount of time|
| PENDING SALES| float64| Quantitative Discrete| the number of homes that are sold but the process hasn't been completed fully; the count must be a whole number| our research question needs this column to determine how many homes for a specific time frame have not fully finalized their selling process.|



The reason why our group chose the columns above is because those columns tie in directly to the housing market of certain states. They can describe the amount of homes sold, homes that are listed for sale, etc. The columns I left out from the dataset include the year-to-year change columns, which we concluded that its data doesn't help answer the question, region type and region ID, mostly because we just needed to know the name of the states, and frequency because it is apparent from looking at the start and end dates that the frequency is one month so that column is unnecessary. The price of per square foot column was also left out because it does not help one imagine the state of the housing market in specific states.

In [102]:
print(df['PERIOD END'].dtype)
print(df['PERIOD BEGIN'].dtype)
print(df['REGION NAME'].dtype)
print(df['HOMES SOLD'].dtype)
print(df['MEDIAN SALE PRICE NSA ($)'].dtype)
print(df['ACTIVE LISTINGS'].dtype)
print(df['NEW LISTINGS'].dtype)
print(df['PENDING SALES'].dtype)

object
object
object
float64
float64
float64
float64
float64

In [ ]:
df['PERIOD BEGIN'] = pd.to_datetime(df['PERIOD BEGIN'])
df2['PERIOD BEGIN'] = pd.to_datetime(df2['PERIOD BEGIN'])

df['PERIOD END'] = pd.to_datetime(df['PERIOD END'])
df2['PERIOD END'] = pd.to_datetime(df2['PERIOD END'])